### ISSUE TITLE
'RetinaNet' object has no attribute 'get_channel_num'

### ISSUE THREAD

**Issue by yuanli2333** [KaiyuYue/mgd#1]
Hi author,

Thanks a lot for sharing the nice work!
For detection part: RetinaNet-R50->RetinaNet-R18, run the [command](https://github.com/KaiyuYue/mgd/tree/master/d2#2-train-retinanet): 
An error show up.
In mge/builder.py [line61]( self.t_channels = self.t_net.get_channel_num()):
```
line61: self.t_channels = self.t_net.get_channel_num()
AttributeError: 'RetinaNet' object has no attribute 'get_channel_num'
```

**Comment by kaiyuyue** [comment]
This error is expected because the command you use is to train the base RetinaNet.

If you would like to train with MGD, please refer [the 2nd part - Train with MGD](https://github.com/KaiyuYue/mgd/tree/master/d2#2-train-with-mgd) to copy ALL the necessary files into detectron2.

**Comment by yuanli2333** [comment]
> This error is expected because the command you use is to train the base RetinaNet.
> 
> If you would like to train with MGD, please refer [the 2nd part - Train with MGD](https://github.com/KaiyuYue/mgd/tree/master/d2#2-train-with-mgd) to copy ALL the necessary files into detectron2.

Actually, I am training with MGD exactly the same as the 2nd part (I did a wrong refer for the question) as the following:
![image](https://user-images.githubusercontent.com/33076543/91861123-0a00c800-ec9f-11ea-83bf-6d1dda659708.png)

And the error will only happen when train with MGD, but not appear for training the base RetinaNet.

**Comment by KaiyuYue** [comment]
Could you check that the file `detectron2/detectron2/modeling/meta_arch/retinanet.py` has these [functions](https://github.com/KaiyuYue/mgd/blob/master/d2/d2/modeling/meta_arch/retinanet.py#L189-L207) after copying  necessary files into d2 ? I think your this error is caused by the no written permission of your detectron2.

**Comment by kaiyuyue** [comment]
Could you check that the file `detectron2/detectron2/modeling/meta_arch/retinanet.py` has these [functions](https://github.com/KaiyuYue/mgd/blob/master/d2/d2/modeling/meta_arch/retinanet.py#L189-L207) after copying  necessary files into d2 ? I think this error may be caused by the no written permission of your detectron2.

**Comment by yuanli2333** [comment]
> Could you check that the file `detectron2/detectron2/modeling/meta_arch/retinanet.py` has these [functions](https://github.com/KaiyuYue/mgd/blob/master/d2/d2/modeling/meta_arch/retinanet.py#L189-L207) after copying necessary files into d2 ? I think this error may be caused by the no written permission of your detectron2.

Hi,

Thanks for reply!
I found the reason. I built Detectron2 before, while mgd changed the backbone and meta_arch in detectron2. So I need uninstall the Detectron2 from my environment first, and copy the 'd2/modeling' and 'd2/engine' file to 'detectron2/',  then rebuild Detectron2.

**Comment by kaiyuyue** [comment]
Glad about that. But I build detectron2 via `python -m pip install -e detectron2` only once for all the experiments. Then dynamically copying files into it still works well without rebuilding. Hope this could be helpful. :)
