### ISSUE TITLE
Is densenet (as the teacher) compatible with your method?

### ISSUE THREAD

**Issue by UBCDingXin** [KaiyuYue/mgd#2]
Hi there,

Since densenet, not like resnet, has many cross-block connections, I am wondering whether it, as the teacher, is compatible with your method?

**Comment by kaiyuyue** [comment]
Hi,

Personally, I think it is yes. 

From my perspective to discuss, although there are no corresponding experiments about using DenseNet as the teacher, it is to see that MGD helps the student to imitate the output features of the teacher. MGD does not consider how these output features are generated and what architecture creates these output features. So, MGD does not strongly depend on the architectures used in experiments.

Moreover, there is an experiment that ResNet distills ShuffleNet on ImageNet. The ShuffleNet apparently differs from the ResNet in the part of architecture because of the shuffle operation. Thus, I think, no matter the DenseNet will be the teacher or the student, it would work (maybe well like the case of ShuffleNet).

**Comment by UBCDingXin** [comment]
Thanks!

**Comment by UBCDingXin** [comment]
> Hi,
> 
> Personally, I think it is yes.
> 
> From my perspective to discuss, although there are no corresponding experiments about using DenseNet as the teacher, it is to see that MGD helps the student to imitate the output features of the teacher. MGD does not consider how these output features are generated and what architecture creates these output features. So, MGD does not strongly depend on the architectures used in experiments.
> 
> Moreover, there is an experiment that ResNet distills ShuffleNet on ImageNet. The ShuffleNet apparently differs from the ResNet in the part of architecture because of the shuffle operation. Thus, I think, no matter the DenseNet will be the teacher or the student, it would work (maybe well like the case of ShuffleNet).

Thanks!
